# Generated by Django 5.2.5 on 2025-09-02 18:35

import os
from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()
    ADMIN_USERNAME = os.environ.get('ADMIN_USERNAME')
    ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD')

    if User.objects.filter(is_superuser=True).exists():
        print('Superuser already exists, skipping creation.')
        return

    if ADMIN_USERNAME and ADMIN_PASSWORD:
        User.objects.create_superuser(
            username=ADMIN_USERNAME,
            password=ADMIN_PASSWORD
        )
        print(f'Superuser "{ADMIN_USERNAME}" created successfully.')
    else:
        print('ADMIN_USERNAME or ADMIN_PASSWORD environment variables not set. Skipping superuser creation.')


class Migration(migrations.Migration):

    dependencies = [
        ("cashbook", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
